DE.plot <- function (output, q = NULL, graphic = c("MD","expr","chrom"),
                     pch = 20, cex = 0.5, col = 1, pch.sel = 1, cex.sel = 0.6, col.sel = 2,
                     log.scale = TRUE, chromosomes = NULL, join = FALSE,...) {
  
  if (class(output) != "Output") 
    stop("Error. You must give the object generated by the noiseq function\n")
  
  graphic <- match.arg(graphic)

  
  ## MD plot
  if (graphic == "MD") {
    
    plot(output@results[[1]][,c("M","D")], pch = pch, xlab = "M", ylab = "D", cex = cex, col = col,...)

    if(!is.null(q))
      mySelection = rownames(degenes(output,q))
      points(output@results[[1]][mySelection,c("M","D")], col = col.sel, pch = pch.sel, cex = cex.sel)

  } 
  
  
  ## Expression plot: Condition1 vs Condition2
  if (graphic == "expr") { 
    
    data <- cbind(output@results[[1]][1],output@results[[1]][2])
    rownames(data) <- rownames(output@results[[1]])
    colnames(data) <- colnames(output@results[[1]][c(1,2)])
    
    if (log.scale) {
      
      k <- min(data, na.rm=TRUE)
      
      plot(log2(data + k), main = "Log2(data)",
           pch = pch, cex = cex, col = col,...)
      
      if(!is.null(q)) {
        
        mySelection = rownames(degenes(output,q))  
        points(log2(data[mySelection,] + k),col = col.sel, pch = pch.sel, cex = cex.sel)
      }
      
    } else {
      
      plot(data, main = "Expression data", pch = pch, cex = cex, col = col,...)
      
      if(!is.null(q)) {
        
        mySelection = rownames(degenes(output,q))  
        points(data[mySelection,], col = col.sel, pch = pch.sel, cex = cex.sel)
        
      }
    }
  }
  
  
  ## MANHATTAN PLOT
  if (graphic == "chrom") {
    
    mydata <- cbind(output@results[[1]][,8:10],output@results[[1]][,1:2])
    mydata <- na.omit(mydata)
    
    colnames(mydata) <- c("chr", "start", "end", colnames(mydata)[-c(1:3)])
    
    mydata[,"chr"] <- as.character(as.roman(mydata[,"chr"]))
    
    if (is.null(chromosomes)) {  # todos los cromosomas
      chromosomes <- unique(mydata$chr)
    }
    
    # logarithmic scale
    if (log.scale) {
      if(min(mydata[,-c(1:3)], na.rm = TRUE) < 1) {
        kk <- -min(mydata[,-c(1:3)], na.rm = TRUE)+1
      } else { kk <- 0 }
      mydata[,-c(1:3)] <- log2(mydata[,-c(1:3)]+kk)
    }  
    
    # selecting data from chromosomes to paint
    mydata <- mydata[which(mydata[,"chr"] %in% chromosomes),]
    
    # change chromosomes to roman numbers to order them well
    allchr.roman <- as.roman(mydata$chr)
    
    # ordering data by chromosome and start position
    ordenat <- mydata[order(allchr.roman, mydata[,"start"]),]
    
    # ordering (in roman numbers) the chromosomes to paint
    chr.roman <- chromosomes[order(as.roman(chromosomes))]
    
    sel.ord <- NULL
    if (!is.null(q)) {
      # up-regulated in first condition
      cond1 <- rownames(degenes(output,q,M="up"))
      # up-regulated in second condition
      cond2 <- rownames(degenes(output,q,M="down"))
      
      cond1 <- (rownames(ordenat) %in% cond1)*1
      cond2 <- (rownames(ordenat) %in% cond2)*1
      
      sel.ord  <- cbind(cond1, cond2)
      rownames(sel.ord) <- rownames(ordenat)
    }
    
    chr.long <- aggregate(ordenat[,"end"],
                          by = list(as.character(ordenat[,"chr"])), max)
    chr.long <- chr.long[order(as.roman(as.character(chr.long[,1]))),]
    
    
    if (join) { # si todos los cromosomas van en el mismo plot
      
      total.long <- sum(as.numeric(chr.long$x))
      
      chr.start <- cumsum(c(1,chr.long$x[-length(chr.long$x)]))
      names(chr.start) <- chr.long[,1]
      
      plot(c(1,total.long), c(-max(ordenat[,5]), max(ordenat[,4])),
           type = "n", xlab = "", ylab = "Expression data", xaxt = "n")
      
      axis(side = 1, at = chr.start, labels = chr.long[,1], font = 2)
      
      abline(h = 0, lty = 2, lwd = 0.5)    
      
      for (ch in chr.roman) {
        
        dat.chr <- ordenat[which(ordenat[,"chr"] == ch),]
        dat.chr[,c("start","end")] <- dat.chr[,c("start","end")] +
          chr.start[ch] - 1
        
        rect(xleft = dat.chr[,"start"], ybottom = 0,
             xright = dat.chr[,"end"], ytop = dat.chr[,4],
             col = "grey", border = NA)
        
        rect(xleft = dat.chr[,"start"], ybottom = -dat.chr[,5],
             xright = dat.chr[,"end"], ytop = 0,
             col = "grey", border = NA)
        
        if (!is.null(q)) {
          
          aux <- which(rownames(sel.ord) %in% rownames(dat.chr))          
          
          sel.chr1 <- dat.chr[,4]*sel.ord[aux,1]
          sel.chr2 <- -dat.chr[,5]*sel.ord[aux,2]
          
          rect(xleft = dat.chr[,"start"], ybottom = 0,
               xright = dat.chr[,"end"], ytop = sel.chr1,
               col = 2, border = NA)
          
          rect(xleft = dat.chr[,"start"], ybottom = sel.chr2,
               xright = dat.chr[,"end"], ytop = 0,
               col = 3, border = NA)        
        }
        
        segments(x0 = dat.chr[,"start"], y0 = 0, x1 = dat.chr[,"end"],
                 y1 = 0, col = 4, lwd = 0.5) # annotated genes
        
      }        
      
      text(c(1,1), 0.9*c(max(ordenat[,4]), -max(ordenat[,5])),
           colnames(mydata)[4:5], font = 3, adj = 0, col = 2:3)
      
      
      # a plot for each chromosome
    } else {    
      
      num.chr <- length(chromosomes)
      
      k <- 20
      
      long.prop <- round((chr.long$x / min(chr.long$x))*k, 0)
      
      while (max(long.prop)*num.chr > 500 | max(long.prop) > 50) {
        
        k <- k-1
        
        long.prop <- round((chr.long$x / min(chr.long$x))*k, 0)
        
      }
      
      forlayout <- matrix(0, num.chr, max(long.prop))
      
      #print(dim(forlayout))
      
      for (i in 1:num.chr) {
        
        forlayout[i, 1:long.prop[i]] <- i
        
      }
      
      layout(forlayout)
      
      if (num.chr > 1)	par(mar=c(2,4.1,0.1,0.1))
      
      miylim <- c(-max(ordenat[,5], na.rm=TRUE), max(ordenat[,4],na.rm=TRUE))
      
      for (i in 1:num.chr) {
        
        apintar <- ordenat[which(ordenat[,"chr"] ==  chr.roman[i]), 2:5]
        
        plot(c(1,chr.long[i,2]), miylim, type = "n",
             xlab = "", ylab = as.roman(chr.roman[i]), xaxt = "n",
             font.lab = 2, cex.lab = 1.3)
        
        rect(xleft = apintar[,"start"], ybottom = 0, xright = apintar[,"end"],
             ytop = apintar[,3], col = "grey", border = NA)
        
        rect(xleft = apintar[,"start"], ybottom = -apintar[,4],
             xright = apintar[,"end"], ytop = 0, col = "grey", border = NA)
        
        if (!is.null(q)) {
          
          aux <- which(rownames(sel.ord) %in% rownames(apintar))          
          asel <- sel.ord[aux,]*apintar[,3:4]
          
          rect(xleft = apintar[,"start"], ybottom = 0, xright = apintar[,"end"],
               ytop = asel[,1], col = 2, border = NA)
          
          rect(xleft = apintar[,"start"], ybottom = -asel[,2],
               xright = apintar[,"end"], ytop = 0, col = 3, border = NA)        
          
        }      
        
        abline(h = 0, lty = 2, lwd = 0.5)
        
        segments(x0 = apintar[,"start"], y0 = 0, x1 = apintar[,"end"],
                 y1 = 0, col = 4, lwd = 0.5) # annotated genes
        
        etiq <- mypretty(c(1,chr.long[i,2]), n = 10)
        
        axis(side = 1, at = etiq, labels = etiq)
        
        text(c(1,1), 0.9*miylim, colnames(mydata)[5:4],
             font = 3, adj = 0, col = 3:2)
      }
    }
  }
}
  
  
mypretty <- function(x, n = 5) {
  
  mywidth <- diff(x)
  
  mybin <- ceiling(mywidth/(n-1))
  
  mylabels0 <- x[1] + mybin*(0:(n-1))
  
  ndig <- nchar(as.character(mylabels0))
                                        #print(ndig)
  
  mylabels <- mylabels0
  
  k <- 0
  
  for (i in 2:(n-1)) {
    
    mylabels[i] <- (round(mylabels0[i]/10^(ndig[i]-1),k))*10^(ndig[i]-1)
    
    while (mylabels[i] == mylabels[i-1]) {
      
      k <- k+1
      
      mylabels[i] <- (round(mylabels0[i]/10^(ndig[i]-1),k))*10^(ndig[i]-1)
      
    }
    
  }
  
  mylabels
  
}
