##################################################################################
##############      Quality Control Report on Expression Data       ##############
##################################################################################


## By Sonia Tarazona
## 25-June-2013


### Generating data for QC report
##################################


data2report = function(input, samples = NULL, factor = NULL) {
  
  if (!is.null(featureData(input)$Biotype)) {  # BIOTYPES
    mybiotdet = biodetection.dat(input, factor = factor, k = 0); biot.avail = TRUE
    mycountsbio = countsbio.dat(input, factor = factor, quartiles = FALSE)
  } else {  # NO biotypes
    mybiodet = NULL; biot.avail = FALSE
  }
  
  mysat = saturation.dat(input, k = 0, ndepth = 6, newdetections = TRUE)  ### me quedo aqui
  #### necesito saber como sera este plot
    
  
  
  list("data" = list("biodet" = mybiodet, "countsbiot" = mycountsbio),
       "parameters" = list("biotypes" = biot.avail))
  
}



##################################################################################


### Generating QC report
##################################


QCreport = function (input, file = paste("QCreport", format(Sys.time(), "_%Y%b%d_%H:%M:%S"), ".pdf", sep = ""),
                     samples = NULL, factor = NULL) {
  
  
  
  QCinfo = data2report(input = input, samples = samples, factor = factor)
  
    
  
  
  pdf(file, paper = "a4", width = 8.27, height = 11.69)
  
  # Page 1
  layout(matrix(c(1,1,2,2,3,4,5,6), nrow = 4, ncol = 2, byrow = TRUE), heights = c(15,10,38,37))
  
  par(mar = c(0,0,0,0))
  plot(1:10, 1:10, type = "n", axes = FALSE, xlab = "", ylab = "")
  text(5,8, "Quality Control of Expression Data", adj = 0.5, cex = 3, col = "brown3", font = 2)
  text(5,4, paste("Generated by NOISeq on", format(Sys.time(), "%d %b %Y, %H:%M:%S")), 
       adj = 0.5, font = 3, cex = 1.5)
  
  plot(1:10, 1:10, type = "n", axes = FALSE, xlab = "", ylab = "")
  text(5,6, "Biotype detection per condition", adj = 0.5, font = 2, cex = 2, col = "dodgerblue4")
  
  biodetection.plot(mybiotdet)
  
  countsbio.plot(mycountsbio1, toplot = "global", samples = 1)
  countsbio.plot(mycountsbio1, toplot = "global", samples = 2)
  
  
  # Page 2
  layout(matrix(c(1,2,3,8,4,9,1,5,6,8,7,9), nrow = 6, ncol = 2, byrow = FALSE), heights = c(10,35,10,5,35,5))
  
  par(mar = c(0,0,0,0))
  plot(1:10, 1:10, type = "n", axes = FALSE, xlab = "", ylab = "")
  text(5,5, "Sequencing depth & Expression quantification", adj = 0.5, font = 2, cex = 2, col = "dodgerblue4")
  
  saturation.plot(mysaturation, samples = 1:2, toplot = 1, ylim = c(10000,18000), toreport = TRUE)
  countsbio.plot(mycountsbio2, toplot = "global", samples = 1:4)
  
  saturation.plot(mysaturation, samples = 3:4, toplot = 1, ylim = c(10000,18000), toreport = TRUE)
  countsbio.plot(mycountsbio2, toplot = "protein_coding", samples = 1:4)
  
  par(mar = c(0,0,0,0))
  plot.new()
  plot.new()
  
  
  # Page 3
  layout(matrix(c(1,1,2,2,3,4,5,5,6,7), nrow = 5, ncol = 2, byrow = TRUE), heights = c(10,10,35,10,35))
  
  par(mar = c(0,0,0,0))
  plot(1:10, 1:10, type = "n", axes = FALSE, xlab = "", ylab = "")
  text(5,5, "Sequencing bias detection", adj = 0.5, font = 2, cex = 2, col = "dodgerblue4")
  
  plot(1:10, 1:10, type = "n", axes = FALSE, xlab = "", ylab = "")
  text(5,8, "Diagnostic plot for feature length bias", adj = 0.5, font = 4, cex = 1.5, col = "aquamarine4")
  text(5,4, "bla bla bla", adj = 0.5, font = 1, cex = 1.5)
  
  par(mar = c(5.1,4.1,4.1,2.1))
  
  length.plot(mylengthbias)
  
  par(mar = c(0,0,0,0))
  plot(1:10, 1:10, type = "n", axes = FALSE, xlab = "", ylab = "")
  text(5,8, "Diagnostic plot for GC content bias", adj = 0.5, font = 4, cex = 1.5, col = "aquamarine4")
  text(5,4, "bla bla bla", adj = 0.5, font = 1, cex = 1.5)
  par(mar = c(5.1,4.1,4.1,2.1))
  
  length.plot(mylengthbias)
  
  
  # Page 4
  layout(matrix(c(1,1,2,3,4,4), nrow = 3, ncol = 2, byrow = TRUE), heights = c(10,35,50))
  
  par(mar = c(0,0,0,0))
  plot(1:10, 1:10, type = "n", axes = FALSE, xlab = "", ylab = "")
  text(5,8, "Diagnostic plot for differences in count distribution", adj = 0.5, font = 4, cex = 1.5, col = "aquamarine4")
  text(5,4, "bla bla bla", adj = 0.5, font = 1, cex = 1.5)
  
  par(mar = c(5.1,4.1,4.1,2.1))
  cd.plot(myCD, samples = NULL, xlim = c(0,50))
  
  
  
  
  
  
  dev.off()
  
}
  
  
